#!/bin/bash

declare -a source_folders=("math" "random" "controller")
sources=""

for f in "${source_folders[@]}"
do
    sources="$sources src/$f/*.c"
done

wiimake-ar -std=c99 libmml.a $sources
wiimake-ar -std=c99 -O1 libmml_O1.a $sources
wiimake-ar -std=c99 -O2 libmml_O2.a $sources
wiimake-ar -std=c99 -O3 libmml_O3.a $sources
rm src/*/*.o


