#!/bin/bash

declare -a source_folders=("math" "random" "controller")
sources=""

for f in "${source_folders[@]}"
do
    sources="$sources src/$f/*.c"
done

wiimake-ar -std=c99 libmml.a $sources
wiimake-ar -std=c99 -O1 libmml_O1.a $sources
wiimake-ar -std=c99 -O2 libmml_O2.a $sources
wiimake-ar -std=c99 -O3 libmml_O3.a $sources

echo
echo "-O0 lines:"
powerpc-eabi-objdump -D libmml.a | wc -l
echo "-O1 lines:"
powerpc-eabi-objdump -D libmml_O1.a | wc -l
echo "-O2 lines:"
powerpc-eabi-objdump -D libmml_O2.a | wc -l
echo "-O3 lines:"
powerpc-eabi-objdump -D libmml_O3.a | wc -l

rm src/*/*.o


