#!/bin/bash

wiimake-ar libmml.a src/*.c
tar --transform='s|src|include|' -czf mml.tar.gz src/*.h libmml.a
zip mml.zip src/*.h libmml.a

printf "@ src/Controller.h\n@=include/Controller.h" | zipnote -w mml.zip
printf "@ src/EventQueue.h\n@=include/EventQueue.h" | zipnote -w mml.zip
printf "@ src/Malloc.h\n@=include/Malloc.h" | zipnote -w mml.zip
printf "@ src/Math.h\n@=include/Math.h" | zipnote -w mml.zip
printf "@ src/MeleeInfo.h\n@=include/MeleeInfo.h" | zipnote -w mml.zip
printf "@ src/Random.h\n@=include/Random.h" | zipnote -w mml.zip

rm src/*.o
